name: polyred

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  platform_test:
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:

    - name: install gl
      run: |
        sudo apt update
        sudo apt install -y libgl1-mesa-dev xvfb xorg-dev
      if: ${{ runner.os == 'Linux' }}

    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: '1.18.0-rc1'

    - name: TestLinux
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        export DISPLAY=:99.0
        sleep 5s
        go test -v -timeout 60m -coverprofile=coverage.txt -covermode=atomic ./...
      if: ${{ runner.os == 'Linux' }}

    - name: TestOthers
      run: |
        go test -v -timeout 60m -covermode=atomic ./...

    - name: Upload coverage profile
      uses: codecov/codecov-action@v1
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: coverage.txt
      if: ${{ runner.os == 'Linux' }}